import React from "react";

const Paises = () => {
  return [
    {
      key: "Afghanistan",
      text: "Afganistán",
      value: "+93",
      code: "AF",
    },
    {
      key: "Albania",
      text: "Albania",
      value: "+355",
      code: "AL",
    },
    {
      key: "Algeria",
      text: "Argelia",
      value: "+213",
      code: "DZ",
    },
    {
      key: "AmericanSamoa",
      text: "Samoa Americana",
      value: "+1684",
      code: "AS",
    },
    {
      key: "Andorra",
      text: "Andorra",
      value: "+376",
      code: "AD",
    },
    {
      key: "Angola",
      text: "Angola",
      value: "+244",
      code: "AO",
    },
    {
      key: "Anguilla",
      text: "Anguilla",
      value: "+1264",
      code: "AI",
    },
    {
      key: "Antarctica",
      text: "Antártida",
      value: "+672",
      code: "AQ",
    },
    {
      key: "Antigua and Barbuda",
      text: "Antigua y Barbuda",
      value: "+1268",
      code: "AG",
    },
    {
      key: "Argentina",
      text: "Argentina",
      value: "+54",
      code: "AR",
    },
    {
      key: "Armenia",
      text: "Armenia",
      value: "+374",
      code: "AM",
    },
    {
      key: "Aruba",
      text: "Aruba",
      value: "+297",
      code: "AW",
    },
    {
      key: "Australia",
      text: "Australia",
      value: "+61",
      code: "AU",
    },
    {
      key: "Austria",
      text: "Austria",
      value: "+43",
      code: "AT",
    },
    {
      key: "Azerbaijan",
      text: "Azerbaiyán",
      value: "+994",
      code: "AZ",
    },
    {
      key: "Bahamas",
      text: "Bahamas",
      value: "+1242",
      code: "BS",
    },
    {
      key: "Bahrain",
      text: "Baréin",
      value: "+973",
      code: "BH",
    },
    {
      key: "Bangladesh",
      text: "Banglades",
      value: "+880",
      code: "BD",
    },
    {
      key: "Barbados",
      text: "Barbados",
      value: "+1246",
      code: "BB",
    },
    {
      key: "Belarus",
      text: "Bielorrusia",
      value: "+375",
      code: "BY",
    },
    {
      key: "Belgium",
      text: "Bélgica",
      value: "+32",
      code: "BE",
    },
    {
      key: "Belize",
      text: "Belice",
      value: "+501",
      code: "BZ",
    },
    {
      key: "Benin",
      text: "Benin",
      value: "+229",
      code: "BJ",
    },
    {
      key: "Bermuda",
      text: "Bermudas",
      value: "+1441",
      code: "BM",
    },
    {
      key: "Bhutan",
      text: "Butan",
      value: "+975",
      code: "BT",
    },
    {
      key: "Bolivia",
      text: "Bolivia",
      value: "+591",
      code: "BO",
    },
    {
      key: "Bosnia and Herzegovina",
      text: "Bosnia-Herzegovina",
      value: "+387",
      code: "BA",
    },
    {
      key: "Botswana",
      text: "Botsuana",
      value: "+267",
      code: "BW",
    },
    {
      key: "Brazil",
      text: "Brasil",
      value: "+55",
      code: "BR",
    },
    {
      key: "British Indian Ocean Territory",
      text: "Territorio Británico del Océano Índico",
      value: "+246",
      code: "IO",
    },
    {
      key: "Brunei Darussalam",
      text: "Brunei",
      value: "+673",
      code: "BN",
    },
    {
      key: "Bulgaria",
      text: "Bulgaria",
      value: "+359",
      code: "BG",
    },
    {
      key: "Burkina Faso",
      text: "Burkina Faso",
      value: "+226",
      code: "BF",
    },
    {
      key: "Burundi",
      text: "Burundi",
      value: "+257",
      code: "BI",
    },
    {
      key: "Cambodia",
      text: "Camboya",
      value: "+855",
      code: "KH",
    },
    {
      key: "Cameroon",
      text: "Camerún",
      value: "+237",
      code: "CM",
    },
    {
      key: "Canada",
      text: "Canadá",
      value: "+1",
      code: "CA",
    },
    {
      key: "Cape Verde",
      text: "Cabo Verde",
      value: "+238",
      code: "CV",
    },
    {
      key: "Cayman Islands",
      text: "Islas Caimán",
      value: "+ 345",
      code: "KY",
    },
    {
      key: "Central African Republic",
      text: "República Centroafricana",
      value: "+236",
      code: "CF",
    },
    {
      key: "Chad",
      text: "Chad",
      value: "+235",
      code: "TD",
    },
    {
      key: "Chile",
      text: "Chile",
      value: "+56",
      code: "CL",
    },
    {
      key: "China",
      text: "China",
      value: "+86",
      code: "CN",
    },
    {
      key: "Christmas Island",
      text: "Isla de Navidad",
      value: "+61",
      code: "CX",
    },
    {
      key: "Cocos (Keeling) Islands",
      text: "Islas Cocos",
      value: "+61",
      code: "CC",
    },
    {
      key: "Colombia",
      text: "Colombia",
      value: "+57",
      code: "CO",
    },
    {
      key: "Comoros",
      text: "Comoras",
      value: "+269",
      code: "KM",
    },
    {
      key: "Congo",
      text: "Congo",
      value: "+242",
      code: "CG",
    },
    {
      key: "Congo, The Democratic Republic of the",
      text: "República Democrática del Congo",
      value: "+243",
      code: "CD",
    },
    {
      key: "Cook Islands",
      text: "Islas Cook",
      value: "+682",
      code: "CK",
    },
    {
      key: "Costa Rica",
      text: "Costa Rica",
      value: "+506",
      code: "CR",
    },
    {
      key: "Cote d'Ivoire",
      text: "Costa de Marfil",
      value: "+225",
      code: "CI",
    },
    {
      key: "Croatia",
      text: "Croacia",
      value: "+385",
      code: "HR",
    },
    {
      key: "Cuba",
      text: "Cuba",
      value: "+53",
      code: "CU",
    },
    {
      key: "Cyprus",
      text: "Chipre",
      value: "+537",
      code: "CY",
    },
    {
      key: "Czechia",
      text: "Chequia",
      value: "+420",
      code: "CZ",
    },
    {
      key: "Denmark",
      text: "Dinamarca",
      value: "+45",
      code: "DK",
    },
    {
      key: "Djibouti",
      text: "Yibuti",
      value: "+253",
      code: "DJ",
    },
    {
      key: "Dominica",
      text: "Dominica",
      value: "+1767",
      code: "DM",
    },
    {
      key: "Dominican Republic",
      text: "República Dominicana",
      value: "+1849",
      code: "DO",
    },
    {
      key: "Ecuador",
      text: "Ecuador",
      value: "+593",
      code: "EC",
    },
    {
      key: "Egypt",
      text: "Egipto",
      value: "+20",
      code: "EG",
    },
    {
      key: "El Salvador",
      text: "El Salvador",
      value: "+503",
      code: "SV",
    },
    {
      key: "Equatorial Guinea",
      text: "Guinea Ecuatorial",
      value: "+240",
      code: "GQ",
    },
    {
      key: "Eritrea",
      text: "Eritrea",
      value: "+291",
      code: "ER",
    },
    {
      key: "Estonia",
      text: "Estonia",
      value: "+372",
      code: "EE",
    },
    {
      key: "Ethiopia",
      text: "Etiopía",
      value: "+251",
      code: "ET",
    },
    {
      key: "Falkland Islands (Malvinas)",
      text: "Islas Malvinas",
      value: "+500",
      code: "FK",
    },
    {
      key: "Faroe Islands",
      text: "Islas Feroe",
      value: "+298",
      code: "FO",
    },
    {
      key: "Fiji",
      text: "Fiyi",
      value: "+679",
      code: "FJ",
    },
    {
      key: "Finland",
      text: "Finlandia",
      value: "+358",
      code: "FI",
    },
    {
      key: "France",
      text: "Francia",
      value: "+33",
      code: "FR",
    },
    {
      key: "French Guiana",
      text: "Guayana Francesa",
      value: "+594",
      code: "GF",
    },
    {
      key: "French Polynesia",
      text: "Polinesia Francesa",
      value: "+689",
      code: "PF",
    },
    {
      key: "Gabon",
      text: "Gabón",
      value: "+241",
      code: "GA",
    },
    {
      key: "Gambia",
      text: "Gambia",
      value: "+220",
      code: "GM",
    },
    {
      key: "Georgia",
      text: "Georgia",
      value: "+995",
      code: "GE",
    },
    {
      key: "Germany",
      text: "Alemania",
      value: "+49",
      code: "DE",
    },
    {
      key: "Ghana",
      text: "Ghana",
      value: "+233",
      code: "GH",
    },
    {
      key: "Gibraltar",
      text: "Gibraltar",
      value: "+350",
      code: "GI",
    },
    {
      key: "Greece",
      text: "Grecia",
      value: "+30",
      code: "GR",
    },
    {
      key: "Greenland",
      text: "Groenlandia",
      value: "+299",
      code: "GL",
    },
    {
      key: "Grenada",
      text: "Granada",
      value: "+1473",
      code: "GD",
    },
    {
      key: "Guadeloupe",
      text: "Guadalupe",
      value: "+590",
      code: "GP",
    },
    {
      key: "Guam",
      text: "Guam",
      value: "+1671",
      code: "GU",
    },
    {
      key: "Guatemala",
      text: "Guatemala",
      value: "+502",
      code: "GT",
    },
    {
      key: "Guernsey",
      text: "Guernsey",
      value: "+44",
      code: "GG",
    },
    {
      key: "Guinea",
      text: "Guinea",
      value: "+224",
      code: "GN",
    },
    {
      key: "Guinea-Bissau",
      text: "Guinea-Bisau",
      value: "+245",
      code: "GW",
    },
    {
      key: "Guyana",
      text: "Guyana",
      value: "+595",
      code: "GY",
    },
    {
      key: "Haiti",
      text: "Haití",
      value: "+509",
      code: "HT",
    },
    {
      key: "Holy See (Vatican City State)",
      text: "Ciudad del Vaticano",
      value: "+379",
      code: "VA",
    },
    {
      key: "Honduras",
      text: "Honduras",
      value: "+504",
      code: "HN",
    },
    {
      key: "Hong Kong",
      text: "Hong Kong",
      value: "+852",
      code: "HK",
    },
    {
      key: "Hungary",
      text: "Hungría",
      value: "+36",
      code: "HU",
    },
    {
      key: "Iceland",
      text: "Islandia",
      value: "+354",
      code: "IS",
    },
    {
      key: "India",
      text: "India",
      value: "+91",
      code: "IN",
    },
    {
      key: "Indonesia",
      text: "Indonesia",
      value: "+62",
      code: "ID",
    },
    {
      key: "Iran, Islamic Republic of",
      text: "Irán",
      value: "+98",
      code: "IR",
    },
    {
      key: "Iraq",
      text: "Iraq",
      value: "+964",
      code: "IQ",
    },
    {
      key: "Ireland",
      text: "Irlanda",
      value: "+353",
      code: "IE",
    },
    {
      key: "Isle of Man",
      text: "Isla de Man",
      value: "+44",
      code: "IM",
    },
    {
      key: "Israel",
      text: "Israel",
      value: "+972",
      code: "IL",
    },
    {
      key: "Italy",
      text: "Italia",
      value: "+39",
      code: "IT",
    },
    {
      key: "Jamaica",
      text: "Jamaica",
      value: "+1876",
      code: "JM",
    },
    {
      key: "Japan",
      text: "Japón",
      value: "+81",
      code: "JP",
    },
    {
      key: "Jersey",
      text: "Jersey",
      value: "+44",
      code: "JE",
    },
    {
      key: "Jordan",
      text: "Jordania",
      value: "+962",
      code: "JO",
    },
    {
      key: "Kazakhstan",
      text: "Kazajistán",
      value: "+7",
      code: "KZ",
    },
    {
      key: "Kenya",
      text: "Kenia",
      value: "+254",
      code: "KE",
    },
    {
      key: "Kiribati",
      text: "Kiribati",
      value: "+686",
      code: "KI",
    },
    {
      key: "Korea, Democratic People's Republic of",
      text: "Corea del Norte",
      value: "+850",
      code: "KP",
    },
    {
      key: "Korea, Republic of",
      text: "Corea del Sur",
      value: "+82",
      code: "KR",
    },
    {
      key: "Kosovo",
      text: "Kosovo",
      value: "+383",
      code: "XK",
    },
    {
      key: "Kuwait",
      text: "Kuwait",
      value: "+965",
      code: "KW",
    },
    {
      key: "Kyrgyzstan",
      text: "Kirguistán",
      value: "+996",
      code: "KG",
    },
    {
      key: "Lao People's Democratic Republic",
      text: "Laos",
      value: "+856",
      code: "LA",
    },
    {
      key: "Latvia",
      text: "Letonia",
      value: "+371",
      code: "LV",
    },
    {
      key: "Lebanon",
      text: "Líbano",
      value: "+961",
      code: "LB",
    },
    {
      key: "Lesotho",
      text: "Lesoto",
      value: "+266",
      code: "LS",
    },
    {
      key: "Liberia",
      text: "Liberia",
      value: "+231",
      code: "LR",
    },
    {
      key: "Libyan Arab Jamahiriya",
      text: "Libia",
      value: "+218",
      code: "LY",
    },
    {
      key: "Liechtenstein",
      text: "Liechtenstein",
      value: "+423",
      code: "LI",
    },
    {
      key: "Lithuania",
      text: "Lituania",
      value: "+370",
      code: "LT",
    },
    {
      key: "Luxembourg",
      text: "Luxemburgo",
      value: "+352",
      code: "LU",
    },
    {
      key: "Macao",
      text: "Macao",
      value: "+853",
      code: "MO",
    },
    {
      key: "Macedonia, The Former Yugoslav Republic of",
      text: "República de Macedonia",
      value: "+389",
      code: "MK",
    },
    {
      key: "Madagascar",
      text: "Madagascar",
      value: "+261",
      code: "MG",
    },
    {
      key: "Malawi",
      text: "Malaui",
      value: "+265",
      code: "MW",
    },
    {
      key: "Malaysia",
      text: "Malasia",
      value: "+60",
      code: "MY",
    },
    {
      key: "Maldives",
      text: "Maldivas",
      value: "+960",
      code: "MV",
    },
    {
      key: "Mali",
      text: "Malí",
      value: "+223",
      code: "ML",
    },
    {
      key: "Malta",
      text: "Malta",
      value: "+356",
      code: "MT",
    },
    {
      key: "Marshall Islands",
      text: "Islas Marshall",
      value: "+692",
      code: "MH",
    },
    {
      key: "Martinique",
      text: "Martinica",
      value: "+596",
      code: "MQ",
    },
    {
      key: "Mauritania",
      text: "Mauritania",
      value: "+222",
      code: "MR",
    },
    {
      key: "Mauritius",
      text: "Mauricio",
      value: "+230",
      code: "MU",
    },
    {
      key: "Mayotte",
      text: "Mayotte",
      value: "+262",
      code: "YT",
    },
    {
      key: "Mexico",
      text: "México",
      value: "+52",
      code: "MX",
    },
    {
      key: "Micronesia, Federated States of",
      text: "Estados Federados de Micronesia",
      value: "+691",
      code: "FM",
    },
    {
      key: "Moldova, Republic of",
      text: "Moldavia",
      value: "+373",
      code: "MD",
    },
    {
      key: "Monaco",
      text: "Monaco",
      value: "+377",
      code: "MC",
    },
    {
      key: "Mongolia",
      text: "Mongolia",
      value: "+976",
      code: "MN",
    },
    {
      key: "Montenegro",
      text: "Montenegro",
      value: "+382",
      code: "ME",
    },
    {
      key: "Montserrat",
      text: "Montserrat",
      value: "+1664",
      code: "MS",
    },
    {
      key: "Morocco",
      text: "Marruecos",
      value: "+212",
      code: "MA",
    },
    {
      key: "Mozambique",
      text: "Mozambique",
      value: "+258",
      code: "MZ",
    },
    {
      key: "Myanmar",
      text: "Birmania",
      value: "+95",
      code: "MM",
    },
    {
      key: "Namibia",
      text: "Namibia",
      value: "+264",
      code: "NA",
    },
    {
      key: "Nauru",
      text: "Nauru",
      value: "+674",
      code: "NR",
    },
    {
      key: "Nepal",
      text: "Nepal",
      value: "+977",
      code: "NP",
    },
    {
      key: "Netherlands",
      text: "Holanda",
      value: "+31",
      code: "NL",
    },
    {
      key: "Netherlands Antilles",
      text: "Antillas Holandesas",
      value: "+599",
      code: "AN",
    },
    {
      key: "New Caledonia",
      text: "Nueva Caledonia",
      value: "+687",
      code: "NC",
    },
    {
      key: "New Zealand",
      text: "Nueva Zelanda",
      value: "+64",
      code: "NZ",
    },
    {
      key: "Nicaragua",
      text: "Nicaragua",
      value: "+505",
      code: "NI",
    },
    {
      key: "Niger",
      text: "Niger",
      value: "+227",
      code: "NE",
    },
    {
      key: "Nigeria",
      text: "Nigeria",
      value: "+234",
      code: "NG",
    },
    {
      key: "Niue",
      text: "Niue",
      value: "+683",
      code: "NU",
    },
    {
      key: "NorfolkIsland",
      text: "IslaNorfolk",
      value: "+672",
      code: "NF",
    },
    {
      key: "NorthernMarianaIslands",
      text: "IslasMarianasdelNorte",
      value: "+1670",
      code: "MP",
    },
    {
      key: "Norway",
      text: "Noruega",
      value: "+47",
      code: "NO",
    },
    {
      key: "Oman",
      text: "Omán",
      value: "+968",
      code: "OM",
    },
    {
      key: "Pakistan",
      text: "Pakistán",
      value: "+92",
      code: "PK",
    },
    {
      key: "Palau",
      text: "Palaos",
      value: "+680",
      code: "PW",
    },
    {
      key: "Panama",
      text: "Panamá",
      value: "+507",
      code: "PA",
    },
    {
      key: "Papua New Guinea",
      text: "Papúa Nueva Guinea",
      value: "+675",
      code: "PG",
    },
    {
      key: "Paraguay",
      text: "Paraguay",
      value: "+595",
      code: "PY",
    },
    {
      key: "Peru",
      text: "Perú",
      value: "+51",
      code: "PE",
    },
    {
      key: "Philippines",
      text: "Filipinas",
      value: "+63",
      code: "PH",
    },
    {
      key: "Pitcairn",
      text: "Islas Pitcairn",
      value: "+872",
      code: "PN",
    },
    {
      key: "Poland",
      text: "Polonia",
      value: "+48",
      code: "PL",
    },
    {
      key: "Portugal",
      text: "Portugal",
      value: "+351",
      code: "PT",
    },
    {
      key: "Puerto Rico",
      text: "Puerto Rico",
      value: "+1939",
      code: "PR",
    },
    {
      key: "Qatar",
      text: "Qatar",
      value: "+974",
      code: "QA",
    },
    {
      key: "Romania",
      text: "Rumania",
      value: "+40",
      code: "RO",
    },
    {
      key: "Russia",
      text: "Rusia",
      value: "+7",
      code: "RU",
    },
    {
      key: "Rwanda",
      text: "Ruanda",
      value: "+250",
      code: "RW",
    },
    {
      key: "Réunion",
      text: "Reunion",
      value: "+262",
      code: "RE",
    },
    {
      key: "Saint Barthélemy",
      text: "San Bartolome",
      value: "+590",
      code: "BL",
    },
    {
      key: "Saint Helena, Ascension and Tristan Da Cunha",
      text: "Santa Elena, Ascensión y Tristán de Acuña",
      value: "+290",
      code: "SH",
    },
    {
      key: "Saint Kitts and Nevis",
      text: "San Cristóbal y Nieves",
      value: "+1869",
      code: "KN",
    },
    {
      key: "Saint Lucia",
      text: "Santa Lucía",
      value: "+1758",
      code: "LC",
    },
    {
      key: "Saint Martin",
      text: "Isla de San Martín",
      value: "+590",
      code: "MF",
    },
    {
      key: "Saint Pierre and Miquelon",
      text: "San Pedro y Miquelon",
      value: "+508",
      code: "PM",
    },
    {
      key: "Saint Vincent and the Grenadines",
      text: "San Vicente y las Granadinas",
      value: "+1784",
      code: "VC",
    },
    {
      key: "Samoa",
      text: "Samoa",
      value: "+685",
      code: "WS",
    },
    {
      key: "San Marino",
      text: "San Marino",
      value: "+378",
      code: "SM",
    },
    {
      key: "Sao Tome and Principe",
      text: " Santo Tomé y Príncipe",
      value: "+239",
      code: "ST",
    },
    {
      key: "Saudi Arabia",
      text: "Arabia Saudita",
      value: "+966",
      code: "SA",
    },
    {
      key: "Senegal",
      text: "Senegal",
      value: "+221",
      code: "SN",
    },
    {
      key: "Serbia",
      text: "Serbia",
      value: "+381",
      code: "RS",
    },
    {
      key: "Seychelles",
      text: "Seychelles",
      value: "+248",
      code: "SC",
    },
    {
      key: "Sierra Leone",
      text: "Sierra Leona",
      value: "+232",
      code: "SL",
    },
    {
      key: "Singapore",
      text: "Singapur",
      value: "+65",
      code: "SG",
    },
    {
      key: "Slovakia",
      text: "Eslovaquia",
      value: "+421",
      code: "SK",
    },
    {
      key: "Slovenia",
      text: "Eslovenia",
      value: "+386",
      code: "SI",
    },
    {
      key: "Solomon Islands",
      text: "Islas Salomón",
      value: "+677",
      code: "SB",
    },
    {
      key: "Somalia",
      text: "Somalia",
      value: "+252",
      code: "SO",
    },
    {
      key: "South Africa",
      text: "Sudáfrica",
      value: "+27",
      code: "ZA",
    },
    {
      key: "South Sudan",
      text: "Sudán del Sur",
      value: "+211",
      code: "SS",
    },
    {
      key: "Spain",
      text: "España",
      value: "+34",
      code: "ES",
    },
    {
      key: "Sri Lanka",
      text: "Sri Lanka",
      value: "+94",
      code: "LK",
    },
    {
      key: "State of Palestine",
      text: "Estado de Palestina",
      value: "+970",
      code: "PS",
    },
    {
      key: "Sudan",
      text: "Sudán",
      value: "+249",
      code: "SD",
    },
    {
      key: "Suriname",
      text: "Surinam",
      value: "+597",
      code: "SR",
    },
    {
      key: "Svalbard and Jan Mayen",
      text: "Svalbard y Jan Mayen",
      value: "+47",
      code: "SJ",
    },
    {
      key: "Swaziland",
      text: "Suazilandia",
      value: "+268",
      code: "SZ",
    },
    {
      key: "Sweden",
      text: "Suecia",
      value: "+46",
      code: "SE",
    },
    {
      key: "Switzerland",
      text: "Suiza",
      value: "+41",
      code: "CH",
    },
    {
      key: "Syrian Arab Republic",
      text: "Siria",
      value: "+963",
      code: "SY",
    },
    {
      key: "Taiwan, Province of China",
      text: "Taiwán",
      value: "+886",
      code: "TW",
    },
    {
      key: "Tayikistan",
      text: "Tayikistán",
      value: "+992",
      code: "TJ",
    },
    {
      key: "Tanzania, United Republic of",
      text: "Tanzania",
      value: "+255",
      code: "TZ",
    },
    {
      key: "Thailand",
      text: "Tailandia",
      value: "+66",
      code: "TH",
    },
    {
      key: "Timor-Leste",
      text: "Timor Oriental",
      value: "+670",
      code: "TL",
    },
    {
      key: "Togo",
      text: "Togo",
      value: "+228",
      code: "TG",
    },
    {
      key: "Tokelau",
      text: "Tokelau",
      value: "+690",
      code: "TK",
    },
    {
      key: "Tonga",
      text: "Tonga",
      value: "+676",
      code: "TO",
    },
    {
      key: "Trinidad and Tobago",
      text: "Trinidad y Tobago",
      value: "+1868",
      code: "TT",
    },
    {
      key: "Tunisia",
      text: "Túnez",
      value: "+216",
      code: "TN",
    },
    {
      key: "Tukey",
      text: "Turqía",
      value: "+90",
      code: "TR",
    },
    {
      key: "Turkmenistan",
      text: "Turkmenistán",
      value: "+993",
      code: "TM",
    },
    {
      key: "Turks and Caicos Islands",
      text: "Islas Turcas y Caicos",
      value: "+1649",
      code: "TC",
    },
    {
      key: "Tuvalu",
      text: "Tuvalu",
      value: "+688",
      code: "TV",
    },
    {
      key: "Uganda",
      text: "Uganda",
      value: "+256",
      code: "UG",
    },
    {
      key: "Ukraine",
      text: "Ucrania",
      value: "+380",
      code: "UA",
    },
    {
      key: "United Arab Emirates",
      text: "Emiratos Árabes Unidos",
      value: "+971",
      code: "AE",
    },
    {
      key: "United Kingdom",
      text: "Reino Unido",
      value: "+44",
      code: "GB",
    },
    {
      key: "United States",
      text: "Estados Unidos",
      value: "+1",
      code: "US",
    },
    {
      key: "Uruguay",
      text: "Uruguay",
      value: "+598",
      code: "UY",
    },
    {
      key: "Uzbekistan",
      text: "Uzbekistán",
      value: "+998",
      code: "UZ",
    },
    {
      key: "Vanuatu",
      text: "Vanuatu",
      value: "+678",
      code: "VU",
    },
    {
      key: "Venezuela, Bolivarian Republic of",
      text: "Venezuela",
      value: "+58",
      code: "VE",
    },
    {
      key: "Vietnam",
      text: "Vietnam",
      value: "+84",
      code: "VN",
    },
    {
      key: "Virgin Islands, British",
      text: "Islas Vírgenes Británicas",
      value: "+1284",
      code: "VG",
    },
    {
      key: "Virgin Islands, U.S.",
      text: "Islas Vírgenes de los Estados Unidos",
      value: "+1340",
      code: "VI",
    },
    {
      key: "Wallis and Futuna",
      text: "Wallis y Futuna",
      value: "+681",
      code: "WF",
    },
    {
      key: "Yemen",
      text: "Yemen",
      value: "+967",
      code: "YE",
    },
    {
      key: "Zambia",
      text: "Zambia",
      value: "+260",
      code: "ZM",
    },
    {
      key: "Zimbabwe",
      text: "Zimbabue",
      value: "+263",
      code: "ZW",
    },
    {
      key: "Åland Islands",
      text: "Åland",
      value: "+358",
      code: "AX",
    },
  ];
};

export default Paises;
